name: Feature builds
on: 
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!main'     # excludes master
      - '!master'   # excludes master

jobs:
  builds:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - name: Build
        run: dotnet build --configuration Release -o temp

      - name: Build package file
        run: |
          Compress-Archive ./temp/* package.zip